### ISSUE TITLE
Controls

### ISSUE THREAD

**Issue by jgdeaton** [pvcraven/2018_cis390ag#1]
Suggested Controls – 
Move – Arrow keys
Jump – Space
Shoot – X 
	Reload - R
Inventory – Tab
Dash – LShift
Melee – C
Inv Nav – Arrow keys
Ctrl – Aim, U,D,L,R, DIAGONAL

**Comment by NanoBytesInc** [comment]
I think there should be at least two buttons for each action, one for a right handed player and one for a left handed player.

**Comment by wolffcaleb** [comment]
I think 'X' would be hard to reach for a 'WASD' movement control set.

**Comment by NateHawk85** [comment]
I feel as though left hand (WASD, spacebar) should be used for movement and the mouse should be used for aiming/shooting.

**Comment by jgdeaton** [comment]
Could we decide on default controls then allow for users to change them. Code based on actions not keys pressed. The question is whether to use just the keyboard or @NateHawk85 suggestion of mouse + keyboard input.
