### ISSUE TITLE
Create inventory screen 

### ISSUE THREAD

**Issue by brownk96** [pvcraven/2018_cis390ag#102]

**Comment by avl27** [comment]
https://unity3d.com/learn/tutorials/projects/adventure-game-tutorial/inventory
Found this Unity tutorial on Inventories

**Comment by avl27** [comment]
I created a 'Persistent' scene to place items that are constant throughout the game in, like the inventory.  Seems like a good way to do this.  If you don't like it we can talk about a better way later.

**Comment by Kyle-Hovey** [comment]
Inventory screen looks good
