### ISSUE TITLE
Cabin Artwork

### ISSUE THREAD

**Issue by Kyle-Hovey** [pvcraven/2018_cis390ag#12]
Create a cabin to be used in the woods on Level 1.

**Comment by Kyle-Hovey** [comment]
Created a cabin for use in the mountain level. Also created buildings folder to put it and other building sprites in.
[Commit Lind](https://github.com/pvcraven/2018_cis390ag/commit/38a8c2d6e82b24de11aeefafc4c0ac2b5c6b87e5)

**Comment by ruvimn** [comment]
Closed in sprint 1
