### ISSUE TITLE
Add a pause menu

### ISSUE THREAD

**Issue by NateHawk85** [pvcraven/2018_cis390ag#120]
Create a menu that has the following items:
- Resume
- Settings
- Show Key Bindings
- Exit to Main Menu
- Exit Program

Create functionality for each menu option.

**Comment by avl27** [comment]
I created a 'Persistent' scene to place items that are constant throughout the game in, like the pause menu.  Seems like a good way to do this.  If you don't like it we can talk about a better way later.

**Comment by NateHawk85** [comment]
I was looking around in the documentation for some other stuff and I saw the [PlayerPrefs](https://docs.unity3d.com/ScriptReference/PlayerPrefs.html) class. If you want to use it, great. Otherwise we can use your persistent scene. Whatever works!

**Comment by NateHawk85** [comment]
Modified PauseController and SaveGame files [here](https://github.com/pvcraven/2018_cis390ag/commit/11d578520eb09b48e07e6b8d847f452c300a62b2).
