### ISSUE TITLE
Tory Fighting Animation

### ISSUE THREAD

**Issue by braedeningersoll** [pvcraven/2018_cis390ag#127]
Melee animation with knife. 

All animations must be a multiple of 5 frames total.

**Comment by ruvimn** [comment]
2018_cis390ag/Unity Project/Assets/Sprites/Characters/PCC/Nochvay_ToryFightAnim.png

**Comment by avl27** [comment]
Add frames to make arm more parallel to the ground during stabbing motion.  Fix foot on frame 2 & 3.
