### ISSUE TITLE
Change Speed for clouds

### ISSUE THREAD

**Issue by EliTaue** [pvcraven/2018_cis390ag#147]
Clouds are moving very quickly. Can we make the speed variable adjustable?
Issue #67

**Comment by Kyle-Hovey** [comment]
Cloud speed is adjustable based on the cloud prefab used. As of now, each prefab has a set minimum and maximum speed of that specific type of cloud. Does this need to be adjustable from the cloud manager or is it fine to base the speed on the prefab?

**Comment by EliTaue** [comment]
Speed based on prefabs works well. Keep max speed below 2 or it looks unnatural as the speed is much higher than clouds usually travel. May need to work in small decimals to get natural speeds.
