### ISSUE TITLE
Damage Indicator

### ISSUE THREAD

**Issue by braedeningersoll** [pvcraven/2018_cis390ag#161]
Would it be helpful for the user to have some sort of indication that they are dealing damage to an enemy?
Some quick examples of how we could show this would be:

- Health bars (these I think would be clunky and eat up screen real-estate
- Knock back the enemies when they're hit (could be a simple script that forces the enemy's transform values in the opposite direction from the player a few "feet")
-Tinting the affected enemies a different color, possibly red, for a second or two and returning them to normal.

These same thing could be used for our user as well if we wanted more indication than just their health bar in the HUD UI.

**Comment by pvcraven** [comment]
Color flash for zombies. Different colored flash for Tory

**Comment by justinhovey** [comment]
Closed in Sprint 3
