### ISSUE TITLE
Tory Character Design

### ISSUE THREAD

**Issue by ruvimn** [pvcraven/2018_cis390ag#19]
Since the character's gender is configurable, it will either need two designs or one gender neutral one. I propose the latter avoid stereotyping pixel genders.

**Comment by rhovey15** [comment]
[Tory Sprite](https://github.com/pvcraven/2018_cis390ag/blob/master/Sprite%20Source%20Files/Characters/rhovey_Tory_Body.asel)

**Comment by braedeningersoll** [comment]
Finished Sprint 1.
