### ISSUE TITLE
Create stepping sound effect for grass

### ISSUE THREAD

**Issue by iamaname2** [pvcraven/2018_cis390ag#190]
Create stepping sound effect for grass.

**Comment by braedeningersoll** [comment]
Verifying this now.

**Comment by braedeningersoll** [comment]
Very nice and accurate sound. I think that we should make these walking sounds all just one "foot fall" so that we can create a script or at least a loop that will make sure that when the player walks around that the sound isn't still playing after we stops or anything like that.

**Comment by SamLaw2198** [comment]
Updating the sound to only have one footstep in Issue #281
