### ISSUE TITLE
Artwork Request- River/Lake water

### ISSUE THREAD

**Issue by braedeningersoll** [pvcraven/2018_cis390ag#21]
Need a body of water that could be used in the landscape such as a stream that players could feasibly cross or jump over, or possibly a lake that could block off the end of a possible route.

**Comment by avl27** [comment]
Should probably make into water tiles

**Comment by braedeningersoll** [comment]
I agree, all of our other terrain blocks have been 64x64 so that probably should be the size of them as well.

**Comment by keeganlamparek** [comment]
Approved to close.
