### ISSUE TITLE
Optional Background/Start Screen Music

### ISSUE THREAD

**Issue by wolffcaleb** [pvcraven/2018_cis390ag#224]
I was messing around earlier and figured I'd add this. We can use it if we decide we want to:

https://drive.google.com/file/d/1tRynnq0tNZSzZg2CkGikzxmDhNYHAA62/view?usp=sharing

**Comment by avl27** [comment]
Needs to match Level 1 music more - needs darker tone.  But music is fine, closing in sprint 3.
