### ISSUE TITLE
Tory-Zombie Touching

### ISSUE THREAD

**Issue by rhovey15** [pvcraven/2018_cis390ag#241]
When Tory touches a zombie the game crashes. When Tory touches a zombie he's supposed to take damage and flash red. This might be a bug, because the flashing was working at one point.

**Comment by drewcummings** [comment]
#259 the dying animation for Tory.

**Comment by avl27** [comment]
No longer crashes when play (Training Level & Level 1)

**Comment by Kyle-Hovey** [comment]
Looks good
