### ISSUE TITLE
Implement inventory management

### ISSUE THREAD

**Issue by iamaname2** [pvcraven/2018_cis390ag#284]
Putting items in the inventory, moving items around in the inventory, using items, removing items from inventory.  All need to be implemented.

**Comment by avl27** [comment]
Made another card for 'using items'.  We will need to determine what we want to 'use' right away, and how we want to 'use' items. Issue #325

**Comment by jgdeaton** [comment]
Items can me picked up and show in inventory and then removed and are destroyed. Still need to be moved around.
