### ISSUE TITLE
Mine Cart Artwork

### ISSUE THREAD

**Issue by Kyle-Hovey** [pvcraven/2018_cis390ag#31]
Create Mine Cart to be placed in the mine of Level 1.

**Comment by Kyle-Hovey** [comment]
Minecart artwork created. Included empty and full minecart.
[Commit Link](https://github.com/pvcraven/2018_cis390ag/commit/445e8f4a0969e41af460a99cf9cf7620586eb652)

**Comment by pvcraven** [comment]
Resize to 64x64

**Comment by ruvimn** [comment]
Closed in sprint 1
