### ISSUE TITLE
Tory accelerates when moving

### ISSUE THREAD

**Issue by keeganlamparek** [pvcraven/2018_cis390ag#330]
Tory can accelerate to the point where they can jump past the entire map.

**Comment by keeganlamparek** [comment]
Be able to walk up hill too.

**Comment by rhovey15** [comment]
Closed in Sprint 5
Tory moves at a consistent speed.

**Comment by rhovey15** [comment]
Closed in Sprint 5
Tory moves at a consistent speed.
