### ISSUE TITLE
Unity Crashes when we open level 1

### ISSUE THREAD

**Issue by NanoBytesInc** [pvcraven/2018_cis390ag#358]
Just did a fresh clone ot make sure it is not something on my machine, but Level 1 is broken now...

**Comment by NanoBytesInc** [comment]
![image](https://user-images.githubusercontent.com/12905832/38748329-5b4da5a2-3f13-11e8-9829-bd009fe5efb0.png)

Here is a GIF demonstrating the issue

**Comment by NanoBytesInc** [comment]
I just tested this on the machines in the lab, and the issue is still present. This is not localized to my machine.

**Comment by NanoBytesInc** [comment]
The last good commit was by @pvcraven with the SHA f8f415f98e903d3c0ae0df3ea9e830c22e697f8e
     https://github.com/pvcraven/2018_cis390ag/commit/f8f415f98e903d3c0ae0df3ea9e830c22e697f8e

The broken code starts from @ruvimn commit ff44bafbfd1c03420dc5a7af51e75e7e9c8a080a
     https://github.com/pvcraven/2018_cis390ag/commit/ff44bafbfd1c03420dc5a7af51e75e7e9c8a080a

But I do not know how to rectify this issue now that there are so many commits on top of the bad one.... This is why we always need to test the code before we push it to master...

**Comment by pvcraven** [comment]
Should be fixed

**Comment by Kyle-Hovey** [comment]
As of now it doesn't crash for me.
