### ISSUE TITLE
Create artwork for a practice dummy

### ISSUE THREAD

**Issue by SamLaw2198** [pvcraven/2018_cis390ag#37]
The tutorial is going to have a practice dummy for the player to learn how to use weapons.

**Comment by justinhovey** [comment]
[Training Dummy Sprite](https://github.com/pvcraven/2018_cis390ag/blob/master/Unity%20Project/Assets/Sprites/Objects/jhovey_training_dummy.png)

**Comment by ruvimn** [comment]
Closed in sprint 1
