### ISSUE TITLE
Create tile art for mountainside floor

### ISSUE THREAD

**Issue by braedeningersoll** [pvcraven/2018_cis390ag#45]
For the first level up in the mountains we need the large mass of mountains that the player traverses down. This could be made as one giant art or possible as large sprites that could be layered over one another to create some depth and allow the level designers more variance.

**Comment by keeganlamparek** [comment]
We will be creating tiles for the ground artwork, rather than one large art piece.

**Comment by keeganlamparek** [comment]
Split this ticket into two other issues: #89 #88
