### ISSUE TITLE
Create tile art for grass floor

### ISSUE THREAD

**Issue by iamaname2** [pvcraven/2018_cis390ag#48]
Create art for grass ground.

**Comment by jgdeaton** [comment]
I Uploaded some tile examples to the sprite source files folder of the repository. Feedback on the style would be appreciated. I'm trying to keep the artwork on the simple and sharper side for consistency and accessibility.

**Comment by jgdeaton** [comment]
Item was submitted for sprint. No points but needs checked. We can keep the spray style tiles or delete them if we don't think they're needed.
