### ISSUE TITLE
Explosive Pickup Artwork

### ISSUE THREAD

**Issue by Kyle-Hovey** [pvcraven/2018_cis390ag#54]
Create artwork for explosives that players can pickup.

**Comment by justinhovey** [comment]
[Explosive Pickup Sprite](https://github.com/pvcraven/2018_cis390ag/blob/master/Unity%20Project/Assets/Sprites/Objects/jhovey_Explosives.png)

**Comment by ruvimn** [comment]
Closed in sprint 1
