### ISSUE TITLE
Create dialogue box art

### ISSUE THREAD

**Issue by jgdeaton** [pvcraven/2018_cis390ag#60]
Need artwork to display the text during dialogue.

**Comment by NanoBytesInc** [comment]
This should have 8 individual images. One for each rounded corner, and one for each edge.

* ------- * ------ *
|                         |
|                         |
*                        *
|                         |
|                         |
* ------- * ------ *

Here, the restricts represent the images that will need to be created. The edge images will be repeated in their respective horizontal and vertical directions to allow the box to be big enough to wrap around the text

**Comment by ruvimn** [comment]
Closed in sprint 1
