### ISSUE TITLE
Create Script for Cloud Sprites

### ISSUE THREAD

**Issue by wolffcaleb** [pvcraven/2018_cis390ag#67]
Clouds should move slowly to the left throughout the game.

**Comment by Kyle-Hovey** [comment]
En example is found in the TestingGrounds.unity scene. In order to use you need to create an empty called CloudManager and attach the CloudManager..cs script to it. Then fill the cloudPrefabList with cloud prefabs that have the CloudPrefab.cs script attached to them.
