### ISSUE TITLE
Dialog Mechanics

### ISSUE THREAD

**Issue by NanoBytesInc** [pvcraven/2018_cis390ag#72]
We need to display conversations and exposition to the player

**Comment by NanoBytesInc** [comment]
This should have a box pop up with text. 
This should be easy to run in a script, and should work something like this 

`show_dialog(Character.Tory, "Hi Brother")`
`show_dialog(Character.Tony, "What's Up dawg!")`
`show_dialog(Character.Tory, "Dont die!")`
`show_dialog(Character.Tory, "Opp... I am dead...")`

And in a later iteration this should be done in a dialog.config file, with a tag to initiate a particular scene.

**dialog.conifg**
`[starting_dialog]`
`Tony: "Hi Brother"`
`Terry: "What's Up dawg!"`
`Tony: "Dont die!"`
`Terry: "Opp... I am dead..."`

**Script**
`start_dialog_sequence("starting_dialog")`

**Comment by NanoBytesInc** [comment]
So, right now the script looks like this, but it will be improved soon

x-pos: 3.5
Tory: Hey there little guy!
Zombie: Wrawrrr
Tory: Hmm... And i was hoping that we could be friends...

x-pos: 3.7
Tory: Time to die
Zombie: Errawrwr
***

**Comment by NanoBytesInc** [comment]
this is only implemented in the testing grounds

**Comment by avl27** [comment]
Looks good.  Please implement into Training level for next sprint.  Closed in sprint 3.
