### ISSUE TITLE
Merge conflict not resolved properly

### ISSUE THREAD

**Issue by pvcraven** [pvcraven/2018_cis390ag#81]
This file:

https://github.com/pvcraven/2018_cis390ag/blob/master/Unity%20Project/Assets/Sprites/Vegetation/RHovey_Tree_1.png.meta

and also the RHovey_Rock and RHovey_Cloud were not merged properly. Rather than pick "mine" or "theirs" an unresolved merge conflict was checked in.

**Comment by ruvimn** [comment]
Closed in sprint 1
