### ISSUE TITLE
Create level design for training level

### ISSUE THREAD

**Issue by brownk96** [pvcraven/2018_cis390ag#92]
- flat level, slight variation 
- just tiles, nothing else

**Comment by avl27** [comment]
I made a folder for scenes and put the training level in there.

**Comment by brownk96** [comment]
Spent extra time creating background and foreground details - spent roughly 8 1/2 hours.

**Comment by justinhovey** [comment]
Issue closed in Sprint 2.

**Comment by brownk96** [comment]
Spent additional time re-adding layers, sorting layers, and order in layers from merge deletion issue.
